### ISSUE TITLE
Example in readme throws error 

### ISSUE THREAD

**Issue by vaibhavchellani** [miguelmota/go-solidity-sha3#8]
```
package main

import (
	"encoding/hex"
	"fmt"

	solsha3 "github.com/miguelmota/go-solidity-sha3"
)

func main() {
	types := []string{"bytes1"}
	values := []interface{}{
		"0xa",
	}

	hash := solsha3.SoliditySHA3(types, values)

	fmt.Println(hex.EncodeToString(hash))
}

```

Output
```
panic: interface conversion: interface {} is string, not uint8

goroutine 1 [running]:
github.com/miguelmota/go-solidity-sha3.pack(0x41c5805, 0x6, 0x4188e00, 0xc0000ca700, 0x0, 0x1, 0xc0000fe080, 0xc0000f5e38)
        /Users/vaibhavchellani/go/pkg/mod/github.com/miguelmota/go-solidity-sha3@v0.1.0/solsha3.go:970 +0x1b32
github.com/miguelmota/go-solidity-sha3.solsha3(0xc0000c43d0, 0x1, 0x1, 0xc0000f5f40, 0x1, 0x1, 0xc0000ca660, 0xc0000ca6c0, 0xc0000ca640)
        /Users/vaibhavchellani/go/pkg/mod/github.com/miguelmota/go-solidity-sha3@v0.1.0/solsha3.go:829 +0xd8
github.com/miguelmota/go-solidity-sha3.SoliditySHA3(0xc0000f5f30, 0x2, 0x2, 0xc0000ca700, 0x403b38a, 0x42ee5a0)
        /Users/vaibhavchellani/go/pkg/mod/github.com/miguelmota/go-solidity-sha3@v0.1.0/solsha3.go:768 +0x27c
```

**Comment by sanilborkar** [comment]
Shouldn't it be _bytes_ instead of _bytes1_?
```
types := []string{"bytes"}
```

Works for me:
```
c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470
```
